runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: index.php

# [START env]
env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/marketplace-northeastern-xn-v1:us-east4:backyardmedia-mysql-db;dbname=BackyardMedia
  MYSQL_USER: backyardmedia
  MYSQL_PASSWORD: backyardmedia2018
# [END env]
